"""init

Revision ID: 084f0343325a
Revises:
Create Date: 2024-04-21 20:58:58.260886

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "084f0343325a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_type",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("annual_price", sa.Integer(), nullable=False),
        sa.Column("monthly_price", sa.Integer(), nullable=False),
        sa.Column("start_of_sales", sa.Date(), nullable=True),
        sa.Column("end_of_sales", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user_subscription",
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("payment_method_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NEW", "AWAITING_PAYMENT", "ACTIVE", "AWAITING_RENEWAL", "INACTIVE", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column("start_of_subscription", sa.Date(), nullable=True),
        sa.Column("end_of_subscription", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("modified_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["type_id"], ["subscription_type.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_id", "user_id", "payment_method_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_subscription")
    op.drop_table("subscription_type")
    # ### end Alembic commands ###
