# Generated by Django 4.2.4 on 2024-04-24 20:52

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.indexes.unique_index
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_filmwork_type_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=3072, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('annual_price', models.IntegerField(verbose_name='Annual price')),
                ('monthly_price', models.IntegerField(verbose_name='Monthly price')),
                ('start_of_sales', models.DateTimeField(verbose_name='Start of sales')),
                ('end_of_sales', models.DateTimeField(verbose_name='End of sales')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'content"."subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionsFilmWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'subscription_film_work',
                'verbose_name_plural': 'subscription_film_works',
                'db_table': 'content"."subscription_film_work',
                'indexes': [psqlextra.indexes.unique_index.UniqueIndex(fields=['film_work', 'subscription'], name='film_work_subs_role_idx')],
            },
        ),
    ]
