# Generated by Django 4.2.4 on 2024-04-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_token",
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
